### ISSUE TITLE
Зачем сопротивления?

### ISSUE THREAD

**Issue by GladilovDmitry** [Norovl/meteoClock#5]
Объясните кто-нибудь зачем при подключении аккумулятора ставятся перемычки из сопротивлений 10кОм. Для чего они?

**Comment by Viy19** [comment]
Тоже интересно, зачем? Что с ними, что без них разницы никакой не заметил.

**Comment by GladilovDmitry** [comment]
На форуме Гайвера сказали что это что-то вроде делителя напряжения, или предохранителя, на случай слишком большого тока, чтоб порты arduino не спалить.

**Comment by Viy19** [comment]
Не похоже на делитель напряжения. В делителе на каждый порт нужно по два сопротивления. Если ограничивать напряжение, то нужно сопротивление и стабилитрон. Если уменьшить ток, то сопротивление нужно было ставить последовательно порту.

**Comment by Viy19** [comment]
Сделал по своему. Поставил потенциометр в качестве делителя напряжения и настройки порога срабатывания индикатора значка "вилка-батарея" на дисплее. Средний вывод потенциометра подключен к выводу А1 на плате Ардуино, крайние выводы подключены к +Vin (вход от не стабильного внешнего источника напряжения) и к общему "минусу" соответственно. Затем крутим потенциометр до тех пор пока значок "батарея" не сменится на "вилка". Проверяем обратное срабатывание значка при отключении сетевого блока питания. Всё должно чётко переключаться.
[посмотреть как я сделал](http://viy19.ucoz.ru/_ph/1/237395329.jpg)

**Comment by GladilovDmitry** [comment]
Нашел в инете что делители напряжения - когда десятки Ом, а тут 10кОм - это точно "подтяжка" к "земле", чтобы на аналоговых пинах при чтении  напряжения с сетевого адаптера (вроде А0) и акб (вроде А1) не было паразитного наведенного напряжения. В коде видно что эти пины используются для чтения напряжения.
